import type { Metadata } from "next";
import { Manrope, Inter } from "next/font/google";
import "@/globalStyles/reset.css"
import "@/globalStyles/variables.css"
import "@/globalStyles/global.css"
import NavBar from "@/components/layout/nav/NavBar/NavBar";
import classes from "./layout.module.css"
import clsx from "clsx";
import { Stack } from "@/components/ui/Stack/Stack";

const manrope = Manrope({
  variable: "--font-main",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-headings",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(manrope.variable, inter.variable)}>
      <Stack as="body" padding="m" gap="m" direction="row" className={classes["layout"]}>
        <NavBar />
        <main>
          {children}
        </main>
        <div id="portal-root" />
      </Stack>
    </html>
  );
}
