import type { Metadata } from "next";
import { JetBrains_Mono, Geist } from "next/font/google";
import "@/globalStyles/reset.css"
import NavBar from "@/components/layout/nav/NavBar/NavBar";
import classes from "./layout.module.css"
import clsx from "clsx";
import { Stack } from "@/components/ui/Stack/Stack";
import "@/globalStyles/global.css"
import "@/globalStyles/variables.generated.css"
import { ThemeProvider } from "next-themes";
import Header from "@/components/layout/header/Header";
import Card from "@/components/ui/Card/Card";

const manrope = Geist({
  variable: "--font-main",
  subsets: ["latin"],
});

const inter = JetBrains_Mono({
  variable: "--font-headings",
  subsets: ["latin"],
});

const jetBrainsMono = JetBrains_Mono({
  variable: "--font-editor",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={clsx(manrope.variable, inter.variable, jetBrainsMono.variable)} suppressHydrationWarning>
      <Card as="body" spacing="s" className={classes["layout"]}>
        <ThemeProvider>
          <Header />
          <Stack padding="m" gap="m" direction="row">
            <NavBar />
            <main>
              {children}
            </main>
          </Stack>
          <div id="portal-root" />
        </ThemeProvider>
      </Card>
    </html >
  );
}
