import type { Metadata } from "next";
import { Manrope, Inter } from "next/font/google";
import "@/globalStyles/reset.css"
import "@/globalStyles/variables.css"
import "@/globalStyles/global.css"
import NavBar from "@/components/layout/nav/NavBar/NavBar/NavBar";
import classes from "./layout.module.css"
import clsx from "clsx";

const manrope = Manrope({
  variable: "--font-main",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-headings",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={clsx(manrope.variable, inter.variable)}>
      <body className={classes["layout"]}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
